apiVersion: apps/v1
kind: Deployment
metadata:
  name: chirperserver-deployment
  namespace: chirper-ns
  labels:
    app: web
    env: dev
    version: v10673337993
spec:
  selector:
    matchLabels:
      app: web
  replicas: 1
  template:
    metadata:
      labels:
        app: web
        env: dev
    spec:
      imagePullSecrets: 
      - name: dockerhub-secret
      containers:
      - name: chirper
        image: tngvlad/chirperserver:10673337993
        ports:
          - containerPort : 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5