apiVersion: apps/v1
kind: Deployment
metadata:
  name: chirper-silo
  namespace: chirper-ns
  labels:
    app: chirper-silo
    version: v11000152648
spec:
  selector:
    matchLabels:
      app: chirper-silo
  replicas: 1
  template:
    metadata:
      labels:
        app: chirper-silo
        orleans/serviceId: chirper-service
        orleans/clusterId: chirper-cluster
    spec:
      imagePullSecrets: 
      - name: dockerhub-secret
      containers:
      - name: chirper
        image: tngvlad/chirperserver:11000152648
        ports:
          - containerPort: 8080
          - containerPort: 11111
          - containerPort: 30000
          - containerPort: 443
        env:
          - name: ORLEANS_SERVICE_ID
            valueFrom: 
              fieldRef: 
                fieldPath: metadata.labels['orleans/serviceId']
          - name: ORLEANS_CLUSTER_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['orleans/clusterId']
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: DOTNET_SHUTDOWNTIMEOUTSECONDS
            value: "120"
          - name: AZURE_STORAGE_ACCOUNT_NAME
            value: "devstoreaccount1"
          - name: AZURE_STORAGE_ACCOUNT_KEY
            value: "Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw=="  
          - name: AZURE_STORAGE_CLUSTERING_TABLE
            value: "ClusterMembershipTable"
          - name: AZURE_STORAGE_STATUS_TABLE
            value: "AccountState"
          - name: AZURE_STORAGE_TABLE_ENDPOINT
            value: "http://192.168.0.16:10002"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5