apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chirper-server-ingress
  namespace: chirper-ns  
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /  
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: chirper-server-service
            port:
              number: 80