apiVersion: v1
kind: Service
metadata:
  name: chirper-server
  namespace : chirper-ns
spec:
  selector:
    app: web
    env: dev
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP