apiVersion: v1
kind: Service
metadata:
  name: chirper-server-service
  namespace : chirper-ns
spec:
  selector:
    app: chirper-silo
    env: dev
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: dashboard
  type: LoadBalancer