apiVersion: v1
kind: Service
metadata:
  name: chirper-server-service
  namespace : chirper-ns
spec:
  selector:
    app: web
    env: dev
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP