apiVersion: v1
kind: Service
metadata:
  name: chirper-server-service
  namespace: chirper-ns
spec:
  selector:
    app: chirper-silo
  ports:
    - port: 11111
      targetPort: 11111
      protocol: TCP
      name: silo
    - port: 30000
      targetPort: 30000
      protocol: TCP
      name: gateway
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: dashboard
  type: NodePort
