name: Build Docker Container

on:
  push:
    branches:
      - main
      - dev 

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: tngvlad/chirperserver:latest

      - 
        name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - 
        name: Update version in deployment.yaml
        run: |
            sed -i 's/version: v[0-9.]*/version: v${{ github.run_id }}/' Chirper.Server/k8s/deployment.yaml

      - 
        name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update version to ${{ github.run_id }}
          branch: main
          file_pattern: |
            Chirper.Server/k8s/deployment.yaml