name: Build Docker Container

on:
  push:
    branches:
      - main
      - dev 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - 
        name: Get build version
        id: get_version
        run: |
            VERSION=$(docker run --rm -v "$(pwd):/repo" mcr.microsoft.com/dotnet/sdk:8.0 sh -c "dotnet tool install -g GitVersion.Tool && export PATH=\$PATH:/root/.dotnet/tools && gitversion /repo /showvariable MajorMinorPatch").${{ github.run_id }}          
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: tngvlad/chirperserver:${{ env.VERSION }}

      - 
        name: Update version in deployment.yaml
        run: |
            sed -i 's/version: v[0-9.]*/version: v${{ env.VERSION }}/' Chirper.Server/k8s/deployment.yaml

      - 
        name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update version to ${{ env.VERSION }}
          branch: main
          file_pattern: |
            Chirper.Server/k8s/deployment.yaml          